# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LithiumBook' do
  use_frameworks!

  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'
  pod 'ObjectMapper', '~> 2.2'

  # Pods for LithiumBook

end
